version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-runpod-worker:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.24"
      - run: |
          docker build -t $DOCKERHUB_USERNAME/blender-runpod-worker:latest -t $DOCKERHUB_USERNAME/blender-runpod-worker:<< pipeline.number >> -f Dockerfile .
      - run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: |
          docker push $DOCKERHUB_USERNAME/blender-runpod-worker:latest
          docker push $DOCKERHUB_USERNAME/blender-runpod-worker:<< pipeline.number >>

workflows:
  build-worker:
    when:
      matches:
        pattern: "^main$"
        value: << pipeline.git.branch >>
    jobs:
      - build-runpod-worker