version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-runpod-worker:
    docker:
      - image: cimg/node:22.0
    steps:
      - checkout
      - run:
          name: Check for [docker-release] in commit message
          command: |
            COMMIT_MSG=$(git log -1 --pretty=%B)
            if [[ "$COMMIT_MSG" != *"[docker-release]"* ]]; then
              echo "Commit message does not contain [docker-release], skipping build"
              circleci step halt
            fi
            echo "Found [docker-release] in commit message, proceeding with build"
      - setup_remote_docker:
          version: "20.10.24"
      - run: |
          docker build -t $DOCKERHUB_USERNAME/blender-runpod-worker:v6 -t $DOCKERHUB_USERNAME/blender-runpod-worker:<< pipeline.number >> -f Dockerfile .
      - run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: |
          docker push $DOCKERHUB_USERNAME/blender-runpod-worker:v6
          docker push $DOCKERHUB_USERNAME/blender-runpod-worker:<< pipeline.number >>

workflows:
  build-worker:
    jobs:
      - build-runpod-worker